# Generated by Django 6.0 on 2025-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_band_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("Re", "Records"),
                    ("Cl", "Clothing"),
                    ("Po", "Posters"),
                    ("Mi", "Miscellaneous"),
                ],
                max_length=5,
            ),
        ),
    ]
