# Generated by Django 6.0 on 2025-12-27 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_band"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="year",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1990),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
